project_id = "fkbpxsneprdmiskftteo"

[functions.duplicate-agent]
verify_jwt = true

[functions.voiceflow-interact]
verify_jwt = false

[functions.voiceflow-kb]
verify_jwt = true

[functions.send-support-email]
verify_jwt = true