project_id = "fkbpxsneprdmiskftteo"

[functions.duplicate-agent]
verify_jwt = true

[functions.voiceflow-interact]
verify_jwt = false

[functions.widget-loader]
verify_jwt = false

[functions.voiceflow-kb]
verify_jwt = true

[functions.send-support-email]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-agency-checkout]
verify_jwt = true

[functions.check-agency-subscription]
verify_jwt = true

[functions.sync-stripe-plans]
verify_jwt = true

[functions.link-stripe-subscription]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.create-trial-subscription]
verify_jwt = true

[functions.cancel-trial-subscription]
verify_jwt = true

[functions.schedule-trial-reminder-emails]
verify_jwt = false

[functions.get-agencies-overview]
verify_jwt = true

[functions.authenticate-with-context]
verify_jwt = true

[functions.get-client-users]
verify_jwt = true

[functions.get-agency-users]
verify_jwt = true

[functions.widget-file-upload]
verify_jwt = false

[functions.create-text-transcripts]
verify_jwt = false
